apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search
  name: search
spec:
  replicas: 4
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: 618372882904.dkr.ecr.us-east-1.amazonaws.com/search:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: search
    k8s-app: search
  name: search
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7070
  type: LoadBalancer
  selector:
    app: search
