apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  selector:
    matchLabels:
      run: search
  replicas: 1
  template:
    metadata:
      labels:
        run: search
    spec:
      containers:
        - name: search
          image: sarika21/search:latest
          imagePullPolicy: IfNotPresent
          env:           
            - name: SPRING_ELASTICSEARCH_REST_URIS   
              value: elasticsearch:9200
      #imagePullSecrets:
      #  - name: regcred