apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    run: search
spec:
  ports:
    - port: 7070
      protocol: TCP
      targetPort: 7070
  type: LoadBalancer

  selector:
    run: search
